### ISSUE TITLE
马娘数据缺失

### ISSUE THREAD

**Issue by Nenot233** [shinianj/zhenxun_plugin_uma_mn#1]
头像/适应性/详细信息/原案/决胜服/制服均无图片数据

**Comment by shinianj** [comment]
发不出来还是下不下来

**Comment by shinianj** [comment]
本身插件数据是会通过指令自己下载发送的，一开始是不会有图片数据在本地的

**Comment by Nenot233** [comment]
> 本身插件数据是会通过指令自己下载发送的，一开始是不会有图片数据在本地的

好像是是图片数据下载失败

**Comment by shinianj** [comment]
> > 本身插件数据是会通过指令自己下载发送的，一开始是不会有图片数据在本地的
> 
> 好像是是图片数据下载失败

兄弟，网络问题我也不能帮你解决捏
