### ISSUE TITLE
节奏榜模块需要更新一下 现在只能读到旧版的节奏榜

### ISSUE THREAD

**Issue by shlgf** [shinianj/zhenxun_plugin_uma_mn#2]
现在能读到7月的榜单 8月最新他分成巅峰杯和偶像杯两种了，可能需要重新适配一下

**Comment by shinianj** [comment]
现在才看到很不好意思，要明天才能更新了（因为晚上是画画时间）

**Comment by shinianj** [comment]
节奏榜更新已完成，但我觉得我需要更新点其他东西，所以请后天来更新（？）
